Testing and Navigation
warptools/zapps pull request #2
Opened 2022-10-09 15:12 UTC by Storken

## Description
Style the website to look a little more clean and readable, add a navigation to help users easily navigate the pages and add a testing tool so we can see that the links added to the project are pointing to correct locations.

## Tasks
- [x] Add hyperlink tool
- [x] Add navigation
- [x] Add overall styling
- [x] Add logo

2022-10-10 12:42 UTC, warpfork requested changes

2022-10-10 12:42 UTC, warpfork commented on src/compare.md
> +Reason 2: There's a Zapp variant that addresses this -- See the docs on the [Zapp-splay Variation](/variations#zapp-splay).
We should not need to break github links if we take this bit: https://github.com/ipld/ipld/blob/2f010292da7e3d089f2512b175494abe114f1a2a/.site/.eleventy.js#L41-L54

(Applies in many places)

2022-10-10 12:42 UTC, warpfork commented on yarn.lock
> +# yarn lockfile v1
Why this appears?

2022-10-10 12:42 UTC, warpfork commented on src/technology.md
> +    order: 1
Nit: I'd recommend doing 10, 20, 30 style numbering, because there's no particularly convenient way to insert half-steps later.  (It's not clever, but it's practical.)

2022-10-10 12:46 UTC, warpfork commented
I accidentally raced you a little bit yesterday but just pushed now (>.< sorry), and did a bunch of other config wrangling that I shared in https://github.com/warpsys/zapps/pull/3/ .

I'm not actually sure which to go forward with.  I like a bunch of the docs I did over there, but also it's a bit untested, and of course it doesn't include all the styling work you did here, so maybe now there's some synthesis to do ahead.

2022-10-10 17:46 UTC, Storken commented on yarn.lock
> +# yarn lockfile v1
It's so if we have a CI it can rebuild with the exact package-versions that we used locally :)

2022-10-10 18:07 UTC, Storken commented on src/technology.md
> +    order: 1
Hm, if we're going to have that many pages in the navigation we'll probably need to have that in mind when designing the navigation as well 😅 ah well, for now we've only got 3 so i guess we can take that when we get the issue.

2022-10-10 18:12 UTC, chunkydotdev commented
> I accidentally raced you a little bit yesterday but just pushed now (>.< sorry), and did a bunch of other config wrangling that I shared in #3 .
> 
> I'm not actually sure which to go forward with. I like a bunch of the docs I did over there, but also it's a bit untested, and of course it doesn't include all the styling work you did here, so maybe now there's some synthesis to do ahead.

Let's go ahead with the best of both 🙌

2022-10-11 16:54 UTC, warpfork commented on yarn.lock
> +# yarn lockfile v1
Does npm not have lockfiles that are suitable now as well?

I remember a chapter of history where npm did not do correct reproducible things, and yarn was made in order to solve the basics, but I thought npm was also fixed to be correct and reliable now.

I'd rather have fewer tools in the dep tree unless it's for compelling reason.  (Of course, if I'm wrong about npm lockfiles being reasonably reproducible, that's definitely a compelling reason...)

2022-10-11 17:06 UTC, Storken commented on yarn.lock
> +# yarn lockfile v1
Oh, I just started using yarn and then never looked back, but I guess we could just stay with npm of course :)

2022-10-11 18:25 UTC, warpfork approved these changes

2022-10-13 11:39 UTC, merged